---
- name Playbook include and import
  host: all
  become: yes

  vars: 
   mytext: "Privet Vitaly"

  tasks:
  - name Ping test
    ping:

  - name: Create folder1
    file:
      path: /home/secret/folder1
      state: directory
      mode: 0755
  
  - name Create folder2
    file:
    path: /home/secret/folder2
    state: directory
    mode: 0755

  - name: Create file1
    copy:
      dest: /home/secret/file1.txt
      content: |
        Text Line1, in file1
        Text Line2, in file1
        Text Line3, {{ mytext }}

  - name: Create file1
    copy:
      dest: /home/secret/file2.txt
      content: |
        Text Line1, in file2
        Text Line2, in file2
        Text Line3, {{ mytext }}
