---
- name: playbook4
  hosts: all
  become: yes # root


  vars:  # peremennie
   message1: Privet
   message2: World
   secret: XKFKJHFKJDSHFKJSJDKhDF

  tasks:
  - name: Privet secret 
    debug: #vizov peremennih
      var: secret

  - debug: 
      msg: "Secretnoe slovo {{ secret }}" 
  - debug:
      msg: "Vladelets etogo servera ---> {{ owner }} <---- "
  - set_fact: full_message="{{ message1 }} {{ message2 }} from {{ owner }}" # ob'edinenie peremennih
  - debug: 
      var: full_message 
  - debug:
      var: ansible_distribution 
  - shell: uptime
    register: results
  - debug:
      var: results.stdout  
 
