---
- name: Install default apache2
  hosts: k8s-master
  become: yes # root

  tasks:
  - name: Insatll apache
    apt:  name=apache2 state=latest #install apache
  
  - name: Start nginx
    service: name=apache2 state=started enabled=yes #start apache

...
